// Switch Failover Fabric - multiprocess worker harness.
// Copyright 2026 Summon Software Labs.
// SPDX-License-Identifier: Apache-2.0
//
// This executable exists so that the multiprocess suite can drive the real runtime across a real
// operating-system process boundary and over really connected loopback TCP sockets. Nothing here
// is a thread, an in-process stub or a mock transport.
//
// Commands:
//   serve  --port N --root DIR   serve the framed protocol until stdin reaches EOF
//   replay --root DIR            replay a journal and report the durable lineage that survived
//   hold   --root DIR --marker F commit a failure durably, write F, then block on stdin
//
// --root DIR enables durability over that directory; without it the runtime is in memory.
//
// SYNTHETIC: the fabric is generated by sfftest::build_fabric (a synthetic two-tier topology).
// No physical switch, NIC, RDMA device or multi-node fabric is exercised by this program, and no
// result it produces may be reported as physical-hardware evidence.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <memory>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "fixture.hpp"
#include "sff/sff.hpp"

using namespace sff;

namespace {

constexpr int kUsageError = 2;
constexpr int kStartupError = 3;

/// Seconds of validity stamped on a declaration whose request carries no window.
constexpr std::uint64_t kDefaultValidityNs = 3600ull * kNanosPerSecond;

struct Options {
  std::string command;
  std::uint16_t port = 0;
  bool has_port = false;
  std::filesystem::path root;
  bool has_root = false;
  std::filesystem::path marker;
  bool has_marker = false;
};

int fail_startup(const std::string& message) {
  std::fprintf(stderr, "mp_worker: %s\n", message.c_str());
  std::fflush(stderr);
  return kStartupError;
}

void usage() {
  std::fprintf(stderr,
               "usage:\n"
               "  mp_worker serve  --port N --root DIR\n"
               "  mp_worker replay --root DIR\n"
               "  mp_worker hold   --root DIR --marker FILE\n");
  std::fflush(stderr);
}

bool parse_options(int argc, char** argv, Options& out) {
  if (argc < 2) return false;
  out.command = argv[1];
  for (int index = 2; index < argc; ++index) {
    const std::string flag = argv[index];
    const bool has_value = index + 1 < argc;
    if (flag == "--port" && has_value) {
      const char* text = argv[++index];
      char* end = nullptr;
      const long value = std::strtol(text, &end, 10);
      if (end == text || *end != '\0' || value < 0 || value > 65535) return false;
      out.port = static_cast<std::uint16_t>(value);
      out.has_port = true;
    } else if (flag == "--root" && has_value) {
      out.root = std::filesystem::path(argv[++index]);
      out.has_root = true;
    } else if (flag == "--marker" && has_value) {
      out.marker = std::filesystem::path(argv[++index]);
      out.has_marker = true;
    } else {
      return false;
    }
  }
  return true;
}

// ---------------------------------------------------------------------------------------------
// serve
// ---------------------------------------------------------------------------------------------

/// One response carrying exactly the outcome the runtime decided. Refusals are Error frames, so a
/// caller can never mistake a refusal for a result.
void answer_error(Frame& response, Code code, std::string_view detail) {
  response.header.type = MessageType::Error;
  response.payload = encode_error_payload(code, detail);
}

/// The whole protocol surface of the worker. Every request except the bootstrap Hello is
/// authorised through the coordinator's session model *before* anything is executed: a frame whose
/// session identity, epoch, boot incarnation or request sequence does not match the established
/// session is answered with an Error frame and is never executed.
Status handle_request(Coordinator& coordinator, bool durability_enabled, TimestampNs now_ns,
                      const Frame& request, Frame& response) {
  if (request.header.type == MessageType::Hello) {
    Result<HelloRequest> hello = decode_hello_request(request.payload);
    if (!hello.ok()) {
      answer_error(response, hello.status().code(), hello.status().message());
      return Status::success();
    }
    if (hello.value().format_version != kFrameFormatVersion) {
      answer_error(response, Code::VersionMismatch, "frame format version is not supported");
      return Status::success();
    }
    Result<SessionRecord> opened = coordinator.open_session(hello.value().principal);
    if (!opened.ok()) {
      answer_error(response, opened.status().code(), opened.status().message());
      return Status::success();
    }
    HelloResponse ack;
    ack.session = opened.value().id;
    ack.epoch = opened.value().epoch;
    ack.boot_digest = coordinator.boot_digest();
    ack.format_version = kFrameFormatVersion;
    ack.max_payload = static_cast<std::uint32_t>(coordinator.limits().max_frame_payload);
    ack.outcome = Code::Ok;
    response.header.type = MessageType::HelloAck;
    response.payload = encode_hello_response(ack);
    return Status::success();
  }

  // Session authority is the gate: identity alone is not authority, and the epoch, boot
  // incarnation and request sequence must all still be current.
  const Status authorised = coordinator.authorise(request.header.binding());
  if (!authorised.ok()) {
    answer_error(response, authorised.code(), authorised.message());
    return Status::success();
  }

  switch (request.header.type) {
    case MessageType::QueryAuthority: {
      Result<AuthorityQueryRequest> query = decode_authority_query(request.payload);
      if (!query.ok()) {
        answer_error(response, query.status().code(), query.status().message());
        return Status::success();
      }
      Result<AuthorityQuery> authority = coordinator.query_authority(query.value().dependent);
      if (!authority.ok()) {
        answer_error(response, authority.status().code(), authority.status().message());
        return Status::success();
      }
      AuthorityQueryResponse answer;
      answer.outcome = authority.value().outcome;
      answer.reason = authority.value().reason;
      answer.has_authority = authority.value().has_authority;
      answer.active_grants = authority.value().active_grants.size();
      answer.withdrawn_grants = authority.value().withdrawn_grants.size();
      answer.fenced_generations = authority.value().fenced_generations.size();
      answer.digest = authority.value().digest();
      response.header.type = MessageType::AuthorityResult;
      response.payload = encode_authority_response(answer);
      return Status::success();
    }
    case MessageType::DeclareFailure: {
      Result<FailoverRequest> declared = decode_failover_request(request.payload);
      if (!declared.ok()) {
        answer_error(response, declared.status().code(), declared.status().message());
        return Status::success();
      }
      FailureDeclaration declaration;
      declaration.subject = declared.value().subject;
      declaration.source = declared.value().source;
      declaration.observed_at_ns =
          declared.value().observed_at_ns == 0 ? now_ns : declared.value().observed_at_ns;
      declaration.valid_for_ns =
          declared.value().valid_for_ns == 0 ? kDefaultValidityNs : declared.value().valid_for_ns;
      declaration.reason = declared.value().reason;

      Result<FailoverOutcome> outcome = coordinator.declare_failure(declaration);
      if (!outcome.ok()) {
        answer_error(response, outcome.status().code(), outcome.status().message());
        return Status::success();
      }
      FailoverResponse answer;
      answer.outcome = outcome.value().outcome;
      answer.fence_id = outcome.value().fence.raw();
      answer.fence_scope = static_cast<std::uint32_t>(outcome.value().fence_scope);
      answer.closure_complete = !outcome.value().closure.truncated() &&
                                outcome.value().closure.enumerates_every_root();
      answer.closure_members = outcome.value().closure.members.size();
      answer.grants_fenced = outcome.value().grants_fenced;
      answer.closure_digest = outcome.value().closure.digest();
      response.header.type = MessageType::FailoverResult;
      response.payload = encode_failover_response(answer);
      return Status::success();
    }
    case MessageType::QueryRestore: {
      Result<RestoreQueryRequest> query = decode_restore_query(request.payload);
      if (!query.ok()) {
        answer_error(response, query.status().code(), query.status().message());
        return Status::success();
      }
      Result<RestoreDecision> decision = coordinator.evaluate_restore(query.value().dependent);
      if (!decision.ok()) {
        answer_error(response, decision.status().code(), decision.status().message());
        return Status::success();
      }
      RestoreQueryResponse answer;
      answer.outcome = decision.value().outcome;
      answer.reason = decision.value().reason;
      answer.may_restore = decision.value().may_restore;
      answer.effect_verified = decision.value().effect_verified;
      answer.blocking_generations = decision.value().blocking_generations.size();
      response.header.type = MessageType::RestoreResult;
      response.payload = encode_restore_response(answer);
      return Status::success();
    }
    case MessageType::SnapshotRequest: {
      const TopologySnapshot* topology = coordinator.topology();
      const FailureTable* failures = coordinator.failures();
      const AuthorityRegistry* authority = coordinator.authority();
      SnapshotResponse answer;
      answer.outcome = Code::Ok;
      answer.epoch = coordinator.epoch().raw();
      answer.boot_ordinal = coordinator.boot().boot_ordinal();
      answer.switches = topology == nullptr ? 0 : topology->switches().size();
      answer.fences = authority == nullptr ? 0 : authority->fence_count();
      answer.failures = failures == nullptr ? 0 : failures->size();
      answer.active_grants = authority == nullptr ? 0 : authority->active_grant_count();
      answer.retained_events = coordinator.events(coordinator.limits().max_event_records).size();
      answer.durability_enabled = durability_enabled;
      response.header.type = MessageType::SnapshotResult;
      response.payload = encode_snapshot_response(answer);
      return Status::success();
    }
    default:
      answer_error(response, Code::Unsupported,
                   "this worker does not serve that message type");
      return Status::success();
  }
}

int run_serve(const Options& options) {
  ManualClock clock{1000};
  CoordinatorConfig config;
  config.limits = Limits::defaults();
  config.evidence_class = EvidenceClass::Synthetic;
  config.enable_durability = options.has_root;
  if (options.has_root) config.durable_root = options.root;

  Result<std::unique_ptr<Coordinator>> opened = Coordinator::open(config, &clock);
  if (!opened.ok()) {
    return fail_startup("coordinator could not be opened: " + opened.status().to_string());
  }
  std::unique_ptr<Coordinator> coordinator = std::move(opened).value();

  // SYNTHETIC two-tier fabric, generated deterministically in this process.
  Result<sfftest::Fabric> built = sfftest::build_fabric(sfftest::FabricSpec{});
  if (!built.ok()) return fail_startup("synthetic fabric could not be built: " + built.status().to_string());
  const sfftest::Fabric& fabric = built.value();

  Status installed = coordinator->install_topology(fabric.topology);
  if (!installed.ok()) return fail_startup("topology could not be installed: " + installed.to_string());
  installed = coordinator->install_candidates(fabric.candidates);
  if (!installed.ok()) return fail_startup("candidate table could not be installed: " + installed.to_string());

  // Authoritative affirmative health for every generation in the fixture, so the fabric starts
  // out usable and a later failure is a change of state rather than a pre-existing condition.
  std::vector<SwitchKey> keys = fabric.leaf_keys;
  keys.insert(keys.end(), fabric.spine_keys.begin(), fabric.spine_keys.end());
  keys.insert(keys.end(), fabric.replacement_keys.begin(), fabric.replacement_keys.end());
  std::uint64_t next_evidence = 1;
  for (const SwitchKey& key : keys) {
    EvidenceRecord record;
    record.id = EvidenceId(next_evidence++);
    record.kind = EvidenceKind::SwitchHealth;
    record.source = EvidenceSource::FabricManager;
    record.subject = key;
    record.observed_at_ns = clock.now_ns();
    record.valid_for_ns = 60ull * kNanosPerSecond;
    record.health = SwitchHealthState::Healthy;
    record.detail = "SYNTHETIC fixture observation";
    const Status admitted = coordinator->admit_evidence(record);
    if (!admitted.ok()) return fail_startup("health evidence could not be admitted: " + admitted.to_string());
  }

  ServerOptions server_options;
  server_options.bind_address = "127.0.0.1";
  server_options.port = options.has_port ? options.port : 0;
  server_options.limits = Limits::defaults();

  Coordinator* borrowed = coordinator.get();
  Result<std::unique_ptr<FrameServer>> started =
      FrameServer::start(server_options,
                         [borrowed, &clock, durable = options.has_root](const Frame& request,
                                                                        Frame& response) {
                           return handle_request(*borrowed, durable, clock.now_ns(), request,
                                                 response);
                         });
  if (!started.ok()) return fail_startup("frame server could not be started: " + started.status().to_string());
  std::unique_ptr<FrameServer> server = std::move(started).value();

  // Exactly one line on stdout, flushed: the parent reads it from a redirected handle.
  std::printf("READY port=%u epoch=%llu boot=%llu\n", static_cast<unsigned>(server->port()),
              static_cast<unsigned long long>(coordinator->epoch().raw()),
              static_cast<unsigned long long>(coordinator->boot().boot_ordinal()));
  std::fflush(stdout);

  // Serve until the parent closes our stdin. This is a real end-of-file, not a timeout: the
  // parent owns the write end of the pipe and either closes it or kills this process outright.
  while (std::fgetc(stdin) != EOF) {
  }

  const Status stopped = server->stop();
  const Status shut = coordinator->shutdown();
  if (!stopped.ok()) return fail_startup("frame server did not stop cleanly: " + stopped.to_string());
  if (!shut.ok()) return fail_startup("coordinator did not shut down cleanly: " + shut.to_string());
  return 0;
}

// ---------------------------------------------------------------------------------------------
// replay
// ---------------------------------------------------------------------------------------------

struct JournalScan {
  std::size_t records = 0;
  std::size_t corrupt = 0;
  std::size_t torn = 0;
  bool clean = false;
  std::uint64_t last_sequence = 0;
  std::vector<Record> decoded;
};

/// Independent read-only scan of the journal bytes. Used only when the durable store itself
/// refuses to open the journal, so that the refusal can be reported with real numbers instead of
/// a placeholder.
JournalScan scan_journal(const std::filesystem::path& path, const Limits& limits) {
  JournalScan scan;
  std::ifstream input(path, std::ios::binary);
  if (!input) return scan;
  std::vector<std::uint8_t> bytes;
  std::uint8_t chunk[64 * 1024];
  while (input) {
    input.read(reinterpret_cast<char*>(chunk), static_cast<std::streamsize>(sizeof(chunk)));
    const std::streamsize got = input.gcount();
    if (got <= 0) break;
    bytes.insert(bytes.end(), chunk, chunk + static_cast<std::size_t>(got));
  }

  std::size_t offset = 0;
  bool first = true;
  while (offset < bytes.size()) {
    const DecodeResult decoded =
        decode_record(bytes.data() + offset, bytes.size() - offset, limits);
    if (decoded.disposition == DecodeDisposition::Complete) {
      if (!first && decoded.record.header.seq <= scan.last_sequence) {
        scan.corrupt += 1;
        return scan;
      }
      first = false;
      scan.records += 1;
      scan.last_sequence = decoded.record.header.seq;
      scan.clean = decoded.record.header.kind == RecordKind::ShutdownClean;
      scan.decoded.push_back(decoded.record);
      offset += decoded.consumed;
      continue;
    }
    if (decoded.disposition == DecodeDisposition::TornTail) {
      scan.torn += 1;
      return scan;
    }
    scan.corrupt += 1;
    return scan;
  }
  return scan;
}

void print_replay_line(std::size_t records, std::size_t corrupt, std::size_t torn, bool clean,
                       std::uint64_t last_sequence) {
  std::printf("REPLAY records=%llu corrupt=%llu torn=%llu clean=%d last_seq=%llu\n",
              static_cast<unsigned long long>(records),
              static_cast<unsigned long long>(corrupt),
              static_cast<unsigned long long>(torn), clean ? 1 : 0,
              static_cast<unsigned long long>(last_sequence));
  std::fflush(stdout);
}

void print_lineage(const std::vector<Record>& records) {
  for (const Record& record : records) {
    if (record.header.kind == RecordKind::FailureCommitted) {
      const Result<FailureRecord> decoded = decode_failure_record(record.payload);
      if (!decoded.ok()) continue;
      std::printf("LINEAGE failure %llu@%llu\n",
                  static_cast<unsigned long long>(decoded.value().subject.id().raw()),
                  static_cast<unsigned long long>(decoded.value().subject.generation().raw()));
    } else if (record.header.kind == RecordKind::FenceCommitted) {
      const Result<FenceRecord> decoded = decode_fence_record(record.payload);
      if (!decoded.ok()) continue;
      std::printf("LINEAGE fence %llu@%llu\n",
                  static_cast<unsigned long long>(decoded.value().subject.id().raw()),
                  static_cast<unsigned long long>(decoded.value().subject.generation().raw()));
    }
  }
  std::fflush(stdout);
}

int run_replay(const Options& options) {
  StoreOptions store_options;
  store_options.root = options.root;
  store_options.limits = Limits::defaults();
  store_options.mode = OpenMode::OpenOrCreate;
  store_options.durable_writes = true;

  Result<std::unique_ptr<DurableStore>> opened = DurableStore::open(store_options);
  if (!opened.ok()) {
    // A complete record that fails its integrity check is never repaired or skipped, so the store
    // refuses to open the journal at all. Report what an independent scan of the same bytes found
    // and exit non-zero: corruption is an explicit outcome, never an ordinary absence.
    const JournalScan scan =
        scan_journal(store_options.root / "sff.journal", store_options.limits);
    print_replay_line(scan.records, scan.corrupt, scan.torn, false, scan.last_sequence);
    print_lineage(scan.decoded);
    std::fprintf(stderr, "mp_worker replay: journal refused: %s\n",
                 opened.status().to_string().c_str());
    std::fflush(stderr);
    return 1;
  }

  std::unique_ptr<DurableStore> store = std::move(opened).value();
  const ReplayReport& report = store->open_report();
  print_replay_line(report.records.size(), report.corrupt_records, report.torn_records,
                    report.clean_shutdown, report.last_sequence);
  print_lineage(report.records);
  const Status closed = store->close();
  if (!closed.ok()) return fail_startup("durable store did not close cleanly: " + closed.to_string());
  return 0;
}

// ---------------------------------------------------------------------------------------------
// hold
// ---------------------------------------------------------------------------------------------

int run_hold(const Options& options) {
  if (!options.has_root || !options.has_marker) return kUsageError;

  StoreOptions store_options;
  store_options.root = options.root;
  store_options.limits = Limits::defaults();
  store_options.mode = OpenMode::OpenOrCreate;
  store_options.durable_writes = true;

  Result<std::unique_ptr<DurableStore>> opened = DurableStore::open(store_options);
  if (!opened.ok()) return fail_startup("durable store could not be opened: " + opened.status().to_string());
  std::unique_ptr<DurableStore> store = std::move(opened).value();

  const BootIncarnation boot = BootIncarnation::for_current_process(1);
  Status appended = store->append(
      RecordKind::StreamHeader,
      encode_stream_header(kRecordFormatVersion, boot.boot_ordinal(), boot.process_id(), 1,
                           boot.nonce_hi(), boot.nonce_lo()));
  if (!appended.ok()) return fail_startup("stream header could not be committed: " + appended.to_string());

  FailureRecord failure;
  failure.subject = sfftest::skey(2000, 1);  // the synthetic fixture's first spine generation
  failure.evidence = EvidenceId(1);
  failure.epoch = CoordinatorEpoch(1);
  failure.boot = boot;
  failure.observed_at_ns = 1000;
  failure.recorded_at_ns = 1000;
  failure.reason = "SYNTHETIC durable commit taken before an unacknowledged hard kill";
  appended = store->append(RecordKind::FailureCommitted, encode_failure_record(failure));
  if (!appended.ok()) return fail_startup("failure could not be committed: " + appended.to_string());

  // Force the commit to stable storage *before* the marker exists, so the parent's observation of
  // the marker is proof that the failure is durable and not merely buffered.
  const Status synced = store->sync();
  if (!synced.ok()) return fail_startup("commit could not be synced: " + synced.to_string());

  std::ofstream marker(options.marker, std::ios::binary | std::ios::trunc);
  if (!marker) return fail_startup("marker file could not be created");
  const char text[] = "committed\n";
  marker.write(text, static_cast<std::streamsize>(sizeof(text) - 1));
  marker.flush();
  const bool marker_ok = marker.good();
  marker.close();
  if (!marker_ok) return fail_startup("marker file could not be written");

  // Block on stdin: the parent either kills this process outright or closes the pipe.
  while (std::fgetc(stdin) != EOF) {
  }
  const Status closed = store->close();
  if (!closed.ok()) return fail_startup("durable store did not close cleanly: " + closed.to_string());
  return 0;
}

}  // namespace

int main(int argc, char** argv) {
  Options options;
  if (!parse_options(argc, argv, options)) {
    usage();
    return kUsageError;
  }
  if (options.command == "serve") return run_serve(options);
  if (options.command == "replay") {
    if (!options.has_root) {
      usage();
      return kUsageError;
    }
    return run_replay(options);
  }
  if (options.command == "hold") {
    if (!options.has_root || !options.has_marker) {
      usage();
      return kUsageError;
    }
    return run_hold(options);
  }
  usage();
  return kUsageError;
}
