// Switch Failover Fabric - multiprocess, loopback-socket and hard-kill proof.
// Copyright 2026 Summon Software Labs.
// SPDX-License-Identifier: Apache-2.0
//
// SYNTHETIC: the fabric driven here is generated by sfftest::build_fabric (a synthetic two-tier
// topology). No physical switch, NIC, RDMA device or multi-node fabric is exercised, and no result
// of this suite is hardware evidence.
//
// Threads are not a substitute for a process boundary, so every proof below uses independently
// created operating-system processes (tests/mp_worker.cpp) talking over really connected loopback
// TCP sockets. The test owns every process handle it creates and reaps it before returning.
//
// Windows headers must come first so that winsock2.h wins over the deprecated winsock.h that
// windows.h would otherwise pull in.
#ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#  define NOMINMAX
#endif
#include <winsock2.h>
#include <windows.h>

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

#include "fixture.hpp"
#include "sff/sff.hpp"
#include "test_support.hpp"

using namespace sff;
using namespace sfftest;

namespace {

constexpr const char* kHost = "127.0.0.1";
constexpr const char* kJournalName = "sff.journal";

/// Exit code used for every deliberate hard kill. Distinctive on purpose: a process that ended by
/// itself can never be mistaken for one that was terminated.
constexpr unsigned kKillExitCode = 99;

/// Bounded readiness polling budget. Deliberately a pure iteration count with no elapsed-time
/// measurement, no watchdog thread and no correctness dependence on the delay: the loop exits the
/// moment the condition holds, and exhausting the budget is an explicit CHECK failure, never a
/// silent "assume it worked". A hang is a defect to diagnose, not to mask.
constexpr std::size_t kReadinessAttempts = 20000;

// ---------------------------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------------------------

struct Context {
  bool valid = false;
  std::filesystem::path worker;
  std::filesystem::path scratch;
  std::vector<std::filesystem::path> expected_directories;
};

Context& context() {
  static Context value;
  return value;
}

struct Child {
  HANDLE process = nullptr;
  DWORD pid = 0;
  HANDLE stdin_write = nullptr;
  std::filesystem::path capture;
  bool reaped = false;
  unsigned exit_code = 0;
};

/// Every process this suite created, so the last case can prove none of them outlived the test.
std::vector<std::unique_ptr<Child>>& spawned() {
  static std::vector<std::unique_ptr<Child>> value;
  return value;
}

// ---------------------------------------------------------------------------------------------
// Bounded process plumbing (Win32)
// ---------------------------------------------------------------------------------------------

/// Canonical Windows command-line quoting (the algorithm the CRT's argv parser inverts).
std::wstring quote_argument(const std::wstring& argument) {
  if (!argument.empty() && argument.find_first_of(L" \t\n\v\"") == std::wstring::npos) {
    return argument;
  }
  std::wstring result = L"\"";
  std::size_t index = 0;
  while (index < argument.size()) {
    std::size_t backslashes = 0;
    while (index < argument.size() && argument[index] == L'\\') {
      ++index;
      ++backslashes;
    }
    if (index == argument.size()) {
      result.append(backslashes * 2, L'\\');
      break;
    }
    if (argument[index] == L'"') {
      result.append(backslashes * 2 + 1, L'\\');
      result.push_back(L'"');
      ++index;
      continue;
    }
    result.append(backslashes, L'\\');
    result.push_back(argument[index]);
    ++index;
  }
  result.push_back(L'"');
  return result;
}

std::string read_text(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  if (!input) return std::string();
  std::string text;
  std::string line;
  while (std::getline(input, line)) {
    text.append(line);
    text.push_back('\n');
  }
  return text;
}

/// Create a real process with its stdout and stderr redirected to a capture file and its stdin
/// attached to a pipe the parent owns. Owning the pipe is what makes "close stdin" a real
/// end-of-file signal and "TerminateProcess" an immediate, uncatchable crash boundary.
Child* spawn_child(const std::vector<std::string>& arguments, const std::string& tag) {
  if (!context().valid) return nullptr;
  const std::filesystem::path capture = context().scratch / ("capture-" + tag + ".txt");

  SECURITY_ATTRIBUTES attributes{};
  attributes.nLength = sizeof(attributes);
  attributes.bInheritHandle = TRUE;

  HANDLE capture_handle =
      CreateFileW(capture.wstring().c_str(), GENERIC_WRITE | GENERIC_READ,
                  FILE_SHARE_READ | FILE_SHARE_WRITE, &attributes, CREATE_ALWAYS,
                  FILE_ATTRIBUTE_TEMPORARY, nullptr);
  if (capture_handle == INVALID_HANDLE_VALUE) return nullptr;

  HANDLE stdin_read = nullptr;
  HANDLE stdin_write = nullptr;
  if (CreatePipe(&stdin_read, &stdin_write, &attributes, 0) == FALSE) {
    CloseHandle(capture_handle);
    return nullptr;
  }
  // The child must not inherit the write end, or closing ours would never produce end-of-file.
  SetHandleInformation(stdin_write, HANDLE_FLAG_INHERIT, 0);

  std::wstring command_line = quote_argument(context().worker.wstring());
  for (const std::string& argument : arguments) {
    command_line.push_back(L' ');
    command_line.append(quote_argument(std::filesystem::path(argument).wstring()));
  }

  STARTUPINFOW startup{};
  startup.cb = sizeof(startup);
  startup.dwFlags = STARTF_USESTDHANDLES;
  startup.hStdInput = stdin_read;
  startup.hStdOutput = capture_handle;
  startup.hStdError = capture_handle;

  PROCESS_INFORMATION process{};
  const BOOL created =
      CreateProcessW(context().worker.wstring().c_str(), command_line.data(), nullptr, nullptr,
                     TRUE, 0, nullptr, nullptr, &startup, &process);

  CloseHandle(stdin_read);
  CloseHandle(capture_handle);
  if (created == FALSE) {
    CloseHandle(stdin_write);
    return nullptr;
  }
  CloseHandle(process.hThread);

  std::unique_ptr<Child> child(new Child());
  child->process = process.hProcess;
  child->pid = process.dwProcessId;
  child->stdin_write = stdin_write;
  child->capture = capture;
  Child* raw = child.get();
  spawned().push_back(std::move(child));
  return raw;
}

bool has_exited(const Child& child) {
  if (child.process == nullptr) return true;
  return WaitForSingleObject(child.process, 0) == WAIT_OBJECT_0;
}

/// Hard kill.
///
/// Choice: TerminateProcess on the handle CreateProcess already returned.
/// Rationale: std::system("taskkill /F /PID n") would spawn a second process, need a PID lookup
/// and race with PID reuse; TerminateProcess is the same Win32 primitive taskkill uses internally,
/// but it is immediate, needs no lookup, cannot be confused with a clean exit, and cannot be
/// intercepted by the target (no DLL_PROCESS_DETACH handler runs, no atexit handler runs, no
/// buffer is flushed). That is exactly the "power cut" boundary this suite needs.
bool hard_kill(Child& child) {
  if (child.process == nullptr) return false;
  DWORD state = 0;
  if (GetExitCodeProcess(child.process, &state) != FALSE && state == STILL_ACTIVE) {
    if (TerminateProcess(child.process, kKillExitCode) == FALSE) return false;
  }
  if (WaitForSingleObject(child.process, INFINITE) != WAIT_OBJECT_0) return false;
  DWORD code = 0;
  if (GetExitCodeProcess(child.process, &code) == FALSE) return false;
  child.reaped = true;
  child.exit_code = static_cast<unsigned>(code);
  return true;
}

bool wait_for_exit(Child& child) {
  if (child.process == nullptr) return false;
  if (WaitForSingleObject(child.process, INFINITE) != WAIT_OBJECT_0) return false;
  DWORD code = 0;
  if (GetExitCodeProcess(child.process, &code) == FALSE) return false;
  child.reaped = true;
  child.exit_code = static_cast<unsigned>(code);
  return true;
}

/// Close our end of the child's stdin: the child observes a real end-of-file and shuts down.
bool release_stdin(Child& child) {
  if (child.stdin_write == nullptr) return false;
  const bool closed = CloseHandle(child.stdin_write) != FALSE;
  child.stdin_write = nullptr;
  return closed;
}

void close_child(Child& child) {
  if (child.stdin_write != nullptr) {
    CloseHandle(child.stdin_write);
    child.stdin_write = nullptr;
  }
  if (child.process != nullptr) {
    CloseHandle(child.process);
    child.process = nullptr;
  }
  // The capture file is this suite's own temporary file, so it goes with the process.
  std::error_code code;
  if (!child.capture.empty()) std::filesystem::remove(child.capture, code);
}

/// Bounded readiness poll on the capture file. No timeout is measured; the loop simply stops
/// after a fixed number of attempts so that a worker which never becomes ready fails loudly.
bool wait_for_line(const std::filesystem::path& path, const std::string& prefix,
                   std::string& line) {
  for (std::size_t attempt = 0; attempt < kReadinessAttempts; ++attempt) {
    const std::string text = read_text(path);
    std::size_t start = 0;
    while (start < text.size()) {
      std::size_t end = text.find('\n', start);
      if (end == std::string::npos) end = text.size();
      const std::string candidate = text.substr(start, end - start);
      if (candidate.rfind(prefix, 0) == 0) {
        line = candidate;
        return true;
      }
      start = end + 1;
    }
    Sleep(1);
  }
  return false;
}

bool wait_for_file(const std::filesystem::path& path) {
  for (std::size_t attempt = 0; attempt < kReadinessAttempts; ++attempt) {
    std::error_code code;
    if (std::filesystem::exists(path, code) && !code) return true;
    Sleep(1);
  }
  return false;
}

struct ReadyInfo {
  std::uint16_t port = 0;
  std::uint64_t epoch = 0;
  std::uint64_t boot = 0;
};

bool parse_field(const std::string& line, const std::string& key, std::uint64_t& value) {
  const std::string needle = key;
  const std::size_t position = line.find(needle);
  if (position == std::string::npos) return false;
  std::size_t start = position + needle.size();
  if (start >= line.size()) return false;
  std::uint64_t parsed = 0;
  std::size_t digits = 0;
  while (start < line.size() && line[start] >= '0' && line[start] <= '9') {
    parsed = parsed * 10 + static_cast<std::uint64_t>(line[start] - '0');
    ++start;
    ++digits;
  }
  if (digits == 0) return false;
  value = parsed;
  return true;
}

bool parse_ready(const std::string& line, ReadyInfo& out) {
  if (line.rfind("READY ", 0) != 0) return false;
  std::uint64_t port = 0;
  std::uint64_t epoch = 0;
  std::uint64_t boot = 0;
  if (!parse_field(line, "port=", port)) return false;
  if (!parse_field(line, "epoch=", epoch)) return false;
  if (!parse_field(line, "boot=", boot)) return false;
  if (port == 0 || port > 65535) return false;
  out.port = static_cast<std::uint16_t>(port);
  out.epoch = epoch;
  out.boot = boot;
  return true;
}

// ---------------------------------------------------------------------------------------------
// Worker invocations
// ---------------------------------------------------------------------------------------------

struct RunResult {
  bool exited = false;
  unsigned exit_code = 0;
  std::string output;
};

/// Run a worker command to completion (replay and other bounded commands).
RunResult run_to_completion(const std::vector<std::string>& arguments, const std::string& tag) {
  RunResult result;
  Child* child = spawn_child(arguments, tag);
  if (child == nullptr) return result;
  release_stdin(*child);  // these commands never read stdin
  result.exited = wait_for_exit(*child);
  result.exit_code = child->exit_code;
  result.output = read_text(child->capture);
  std::error_code code;
  std::filesystem::remove(child->capture, code);
  close_child(*child);
  return result;
}

struct ReplayReportText {
  bool parsed = false;
  std::uint64_t records = 0;
  std::uint64_t corrupt = 0;
  std::uint64_t torn = 0;
  std::uint64_t clean = 0;
  std::uint64_t last_sequence = 0;
};

ReplayReportText parse_replay(const std::string& output) {
  ReplayReportText report;
  const std::size_t position = output.find("REPLAY ");
  if (position == std::string::npos) return report;
  const std::string line = output.substr(position);
  report.parsed = parse_field(line, "records=", report.records) &&
                  parse_field(line, "corrupt=", report.corrupt) &&
                  parse_field(line, "torn=", report.torn) &&
                  parse_field(line, "clean=", report.clean) &&
                  parse_field(line, "last_seq=", report.last_sequence);
  return report;
}

bool output_has_lineage(const std::string& output, const std::string& what, const SwitchKey& key) {
  const std::string needle = "LINEAGE " + what + " " + std::to_string(key.id().raw()) + "@" +
                             std::to_string(key.generation().raw());
  return output.find(needle) != std::string::npos;
}

/// Read the journal bytes and report whether a committed fence for exactly this generation is
/// already durable. Used to place the hard kill at an exact durable boundary rather than at a
/// guessed moment.
bool journal_has_fence(const std::filesystem::path& journal, const SwitchKey& key) {
  const Limits limits = Limits::defaults();
  std::ifstream input(journal, std::ios::binary);
  if (!input) return false;
  std::vector<std::uint8_t> bytes;
  std::uint8_t chunk[4096];
  while (input) {
    input.read(reinterpret_cast<char*>(chunk), static_cast<std::streamsize>(sizeof(chunk)));
    const std::streamsize got = input.gcount();
    if (got <= 0) break;
    bytes.insert(bytes.end(), chunk, chunk + static_cast<std::size_t>(got));
  }
  std::size_t offset = 0;
  while (offset < bytes.size()) {
    const DecodeResult decoded =
        decode_record(bytes.data() + offset, bytes.size() - offset, limits);
    if (decoded.disposition != DecodeDisposition::Complete) return false;  // retry on a torn tail
    if (decoded.record.header.kind == RecordKind::FenceCommitted) {
      const Result<FenceRecord> fence = decode_fence_record(decoded.record.payload);
      if (fence.ok() && fence.value().subject == key) return true;
    }
    offset += decoded.consumed;
  }
  return false;
}

bool wait_for_durable_fence(const std::filesystem::path& journal, const SwitchKey& key) {
  for (std::size_t attempt = 0; attempt < kReadinessAttempts; ++attempt) {
    if (journal_has_fence(journal, key)) return true;
    SwitchToThread();
  }
  return false;
}

// ---------------------------------------------------------------------------------------------
// Raw loopback client: the only way to forge a session binding, an epoch, a boot digest or a
// replayed sequence number, which FrameClient deliberately refuses to do.
// ---------------------------------------------------------------------------------------------

class RawClient {
 public:
  RawClient() = default;
  ~RawClient() { close(); }
  RawClient(const RawClient&) = delete;
  RawClient& operator=(const RawClient&) = delete;

  /// Bounded connect-retry: the worker reports READY only after its listener exists, so this
  /// normally succeeds on the first attempt.
  bool connect_loopback(std::uint16_t port) {
    for (std::size_t attempt = 0; attempt < kReadinessAttempts; ++attempt) {
      SOCKET candidate = ::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
      if (candidate == INVALID_SOCKET) return false;
      sockaddr_in address{};
      address.sin_family = AF_INET;
      address.sin_port = htons(port);
      address.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
      if (::connect(candidate, reinterpret_cast<sockaddr*>(&address), sizeof(address)) == 0) {
        socket_ = candidate;
        return true;
      }
      ::closesocket(candidate);
      SwitchToThread();
    }
    return false;
  }

  void close() {
    if (socket_ != INVALID_SOCKET) {
      ::shutdown(socket_, SD_BOTH);
      ::closesocket(socket_);
      socket_ = INVALID_SOCKET;
    }
  }

  bool send_frame(const Frame& frame) {
    const Result<std::vector<std::uint8_t>> encoded = encode_frame(frame, Limits::defaults());
    if (!encoded.ok()) return false;
    std::size_t sent = 0;
    while (sent < encoded.value().size()) {
      const int written =
          ::send(socket_, reinterpret_cast<const char*>(encoded.value().data() + sent),
                 static_cast<int>(encoded.value().size() - sent), 0);
      if (written <= 0) return false;
      sent += static_cast<std::size_t>(written);
    }
    return true;
  }

  bool receive_frame(Frame& out) {
    for (;;) {
      const FrameDecodeResult decoded = decoder_.next();
      if (decoded.disposition == FrameDisposition::Complete) {
        out = decoded.frame;
        return true;
      }
      if (decoded.disposition != FrameDisposition::Incomplete) return false;
      std::uint8_t buffer[4096];
      const int received = ::recv(socket_, reinterpret_cast<char*>(buffer),
                                  static_cast<int>(sizeof(buffer)), 0);
      if (received <= 0) return false;
      if (!decoder_.feed(buffer, static_cast<std::size_t>(received)).ok()) return false;
    }
  }

 private:
  SOCKET socket_ = INVALID_SOCKET;
  FrameStreamDecoder decoder_{Limits::defaults()};
};

Frame make_frame(MessageType type, SessionId session, CoordinatorEpoch epoch,
                 std::uint64_t boot_digest, std::uint64_t sequence,
                 std::vector<std::uint8_t> payload) {
  Frame frame;
  frame.header.magic = kFrameMagic;
  frame.header.format_version = kFrameFormatVersion;
  frame.header.type = type;
  frame.header.session = session;
  frame.header.epoch = epoch;
  frame.header.boot_digest = boot_digest;
  frame.header.request_seq = sequence;
  frame.payload = std::move(payload);
  return frame;
}

/// Answer of a refused request: always an Error frame carrying an explicit code.
struct Refusal {
  bool decoded = false;
  Code code = Code::Unknown;
  std::string detail;
};

Refusal refusal_of(const Frame& frame) {
  Refusal refusal;
  if (frame.header.type != MessageType::Error) return refusal;
  const Result<std::pair<Code, std::string>> decoded = decode_error_payload(frame.payload);
  if (!decoded.ok()) return refusal;
  refusal.decoded = true;
  refusal.code = decoded.value().first;
  refusal.detail = decoded.value().second;
  return refusal;
}

/// A raw socket that has completed the handshake, so forged variants of its own frames can be
/// compared against a frame the worker does accept.
struct RawSession {
  bool opened = false;
  SessionId session;
  CoordinatorEpoch epoch;
  std::uint64_t boot_digest = 0;
  std::uint64_t next_sequence = 2;
};

bool raw_handshake(RawClient& raw, RawSession& session) {
  HelloRequest hello;
  hello.principal = "raw-forge";
  hello.format_version = kFrameFormatVersion;
  Frame request = make_frame(MessageType::Hello, SessionId{}, CoordinatorEpoch{}, 0, 1,
                             encode_hello_request(hello));
  if (!raw.send_frame(request)) return false;
  Frame response;
  if (!raw.receive_frame(response)) return false;
  if (response.header.type != MessageType::HelloAck) return false;
  const Result<HelloResponse> ack = decode_hello_response(response.payload);
  if (!ack.ok() || ack.value().outcome != Code::Ok) return false;
  session.opened = ack.value().session.valid() && ack.value().epoch.valid();
  session.session = ack.value().session;
  session.epoch = ack.value().epoch;
  session.boot_digest = ack.value().boot_digest;
  session.next_sequence = 2;
  return session.opened;
}

// ---------------------------------------------------------------------------------------------
// Typed conversation over FrameClient
// ---------------------------------------------------------------------------------------------

/// The long-lived "serve" worker that cases 1, 2, 3 and 6 drive.
///
/// It is started once, on the first case that needs it, and deliberately outlives those cases:
/// case 2 commits the first failure, case 3 proves forged authority cannot add another, and case 6
/// commits the second failure and then hard-kills this very process to prove what a restart does
/// with the durable state the three cases produced. Cases run in registration order, so this
/// sequence is deterministic rather than incidental.
struct ServeWorker {
  bool attempted = false;
  bool ready = false;
  Child* child = nullptr;
  std::uint16_t port = 0;
  std::uint64_t epoch = 0;
  std::uint64_t boot = 0;
  std::filesystem::path root;
  std::filesystem::path journal() const { return root / kJournalName; }
};

ServeWorker& serve_worker() {
  static ServeWorker worker;
  if (worker.attempted) return worker;
  worker.attempted = true;
  worker.root = context().scratch / "worker-a";
  context().expected_directories.push_back(worker.root);
  Child* child = spawn_child({"serve", "--port", "0", "--root", worker.root.string()}, "serve-a");
  if (child == nullptr) return worker;
  std::string line;
  ReadyInfo info;
  if (wait_for_line(child->capture, "READY", line) && parse_ready(line, info)) {
    worker.child = child;
    worker.port = info.port;
    worker.epoch = info.epoch;
    worker.boot = info.boot;
    worker.ready = true;
    return worker;
  }
  // A worker that never became ready is still reaped, so a failing case cannot leak a process.
  hard_kill(*child);
  close_child(*child);
  return worker;
}

Result<std::unique_ptr<FrameClient>> connect_and_handshake(const ServeWorker& worker,
                                                           const char* principal) {
  Result<std::unique_ptr<FrameClient>> client = FrameClient::connect(kHost, worker.port);
  if (!client.ok()) return client.status();
  const Status handshaken = client.value()->handshake(principal);
  if (!handshaken.ok()) return handshaken;
  return client;
}

Result<AuthorityQueryResponse> ask_authority(FrameClient& client, const DependentRef& dependent) {
  AuthorityQueryRequest request;
  request.dependent = dependent;
  const Result<Frame> response =
      client.call(MessageType::QueryAuthority, encode_authority_query(request));
  if (!response.ok()) return response.status();
  if (response.value().header.type == MessageType::Error) {
    const Result<std::pair<Code, std::string>> error = decode_error_payload(response.value().payload);
    if (!error.ok()) return error.status();
    return Status::failure(error.value().first, error.value().second);
  }
  if (response.value().header.type != MessageType::AuthorityResult) {
    return Status::failure(Code::Invalid, "query authority answered with the wrong message type");
  }
  return decode_authority_response(response.value().payload);
}

Result<FailoverResponse> declare_failure(FrameClient& client, const SwitchKey& subject) {
  FailoverRequest request;
  request.subject = subject;
  request.source = EvidenceSource::FabricManager;
  request.observed_at_ns = 1000;
  request.valid_for_ns = 3600ull * kNanosPerSecond;
  request.reason = "SYNTHETIC fabric manager declaration over loopback";
  const Result<Frame> response =
      client.call(MessageType::DeclareFailure, encode_failover_request(request));
  if (!response.ok()) return response.status();
  if (response.value().header.type == MessageType::Error) {
    const Result<std::pair<Code, std::string>> error = decode_error_payload(response.value().payload);
    if (!error.ok()) return error.status();
    return Status::failure(error.value().first, error.value().second);
  }
  if (response.value().header.type != MessageType::FailoverResult) {
    return Status::failure(Code::Invalid, "declare failure answered with the wrong message type");
  }
  return decode_failover_response(response.value().payload);
}

Result<RestoreQueryResponse> ask_restore(FrameClient& client, const DependentRef& dependent) {
  RestoreQueryRequest request;
  request.dependent = dependent;
  const Result<Frame> response =
      client.call(MessageType::QueryRestore, encode_restore_query(request));
  if (!response.ok()) return response.status();
  if (response.value().header.type == MessageType::Error) {
    const Result<std::pair<Code, std::string>> error = decode_error_payload(response.value().payload);
    if (!error.ok()) return error.status();
    return Status::failure(error.value().first, error.value().second);
  }
  if (response.value().header.type != MessageType::RestoreResult) {
    return Status::failure(Code::Invalid, "restore query answered with the wrong message type");
  }
  return decode_restore_response(response.value().payload);
}

Result<SnapshotResponse> ask_snapshot(FrameClient& client) {
  const Result<Frame> response = client.call(MessageType::SnapshotRequest, {});
  if (!response.ok()) return response.status();
  if (response.value().header.type == MessageType::Error) {
    const Result<std::pair<Code, std::string>> error = decode_error_payload(response.value().payload);
    if (!error.ok()) return error.status();
    return Status::failure(error.value().first, error.value().second);
  }
  if (response.value().header.type != MessageType::SnapshotResult) {
    return Status::failure(Code::Invalid, "snapshot answered with the wrong message type");
  }
  return decode_snapshot_response(response.value().payload);
}

// ---------------------------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------------------------

std::vector<PathId> paths_through(const Fabric& fabric, const SwitchKey& key) {
  std::vector<PathId> result;
  for (const PathDescriptor& path : fabric.topology.paths()) {
    if (std::find(path.hops.begin(), path.hops.end(), key) != path.hops.end()) {
      result.push_back(path.id);
    }
  }
  return result;
}

}  // namespace

// ---------------------------------------------------------------------------------------------
// 1. Readiness and identity: the session adopted from the handshake is the worker's own session.
// ---------------------------------------------------------------------------------------------

SFF_TEST(worker_reports_ready_and_its_reported_identity_is_the_session_identity) {
  CHECK(context().valid);
  if (!context().valid) return;

  ServeWorker& worker = serve_worker();
  CHECK(worker.ready);
  if (!worker.ready) return;
  CHECK_NE(worker.port, 0);
  CHECK_NE(worker.epoch, std::uint64_t{0});
  CHECK_NE(worker.boot, std::uint64_t{0});
  CHECK(std::filesystem::exists(worker.journal()));

  Result<std::unique_ptr<FrameClient>> client = connect_and_handshake(worker, "multiprocess");
  CHECK(client.ok());
  if (!client.ok()) return;
  CHECK(client.value()->handshaken());
  CHECK(client.value()->connected());
  CHECK(client.value()->session().valid());
  CHECK_NE(client.value()->boot_digest(), std::uint64_t{0});

  // Every request carries session + epoch + boot digest + sequence, and the worker refuses any
  // frame whose binding does not match its established session. A successful call is therefore
  // proof that all four match the worker's own identity.
  CHECK_EQ(client.value()->epoch().raw(), worker.epoch);
  CHECK_EQ(client.value()->next_sequence(), std::uint64_t{2});
  {
    Result<Frame> answered = client.value()->call(MessageType::SnapshotRequest, {});
    CHECK(answered.ok());
    CHECK_EQ(client.value()->next_sequence(), std::uint64_t{3});
  }
  Result<SnapshotResponse> snapshot = ask_snapshot(*client.value());
  CHECK(snapshot.ok());
  if (snapshot.ok()) {
    // The snapshot is produced by the worker's own coordinator under the session authority that
    // was just adopted, so its epoch and boot ordinal are the worker's own.
    CHECK_EQ(snapshot.value().outcome, Code::Ok);
    CHECK_EQ(snapshot.value().epoch, worker.epoch);
    CHECK_EQ(snapshot.value().boot_ordinal, worker.boot);
    CHECK(snapshot.value().durability_enabled);
    CHECK_NE(snapshot.value().switches, std::size_t{0});
    CHECK_EQ(snapshot.value().failures, std::size_t{0});
    CHECK_EQ(snapshot.value().fences, std::size_t{0});
    CHECK(snapshot.value().active_grants >= std::size_t{8});
  }
  // A second, independent handshake agrees on the epoch and the boot incarnation and receives a
  // different session: the adopted authority really is the worker's, not a value the client chose.
  {
    Result<std::unique_ptr<FrameClient>> second = connect_and_handshake(worker, "multiprocess-2");
    CHECK(second.ok());
    if (second.ok()) {
      CHECK_NE(second.value()->session().raw(), client.value()->session().raw());
      CHECK_EQ(second.value()->epoch().raw(), client.value()->epoch().raw());
      CHECK_EQ(second.value()->boot_digest(), client.value()->boot_digest());
      CHECK(second.value()->close().ok());
    }
  }
  CHECK(client.value()->close().ok());
}

// ---------------------------------------------------------------------------------------------
// 2. A real failover driven over the socket.
// ---------------------------------------------------------------------------------------------

SFF_TEST(real_failover_over_loopback_fences_the_dependent_and_nothing_else) {
  CHECK(context().valid);
  if (!context().valid) return;
  ServeWorker& worker = serve_worker();
  CHECK(worker.ready);
  if (!worker.ready) return;

  Result<Fabric> built = build_fabric(FabricSpec{});
  CHECK(built.ok());
  if (!built.ok()) return;
  const Fabric& fabric = built.value();
  const SwitchKey failed = fabric.spine_keys.at(0);
  const SwitchKey healthy = fabric.spine_keys.at(1);
  const std::vector<PathId> affected = paths_through(fabric, failed);
  const std::vector<PathId> untouched = paths_through(fabric, healthy);
  CHECK(!affected.empty());
  CHECK(!untouched.empty());
  if (affected.empty() || untouched.empty()) return;

  Result<std::unique_ptr<FrameClient>> client = connect_and_handshake(worker, "failover");
  CHECK(client.ok());
  if (!client.ok()) return;
  FrameClient& session = *client.value();

  // Control: before the failure, every declared dependent holds established authority.
  for (const PathId id : affected) {
    Result<AuthorityQueryResponse> query = ask_authority(session, DependentRef::path(id));
    CHECK(query.ok());
    if (query.ok()) {
      CHECK(query.value().has_authority);
      CHECK_EQ(query.value().outcome, Code::Ok);
    }
  }

  // Fence first: one real declaration, one real fence, over the socket.
  Result<FailoverResponse> outcome = declare_failure(session, failed);
  CHECK(outcome.ok());
  if (!outcome.ok()) return;
  CHECK_EQ(outcome.value().outcome, Code::Ok);
  CHECK_NE(outcome.value().fence_id, std::uint64_t{0});
  CHECK_EQ(outcome.value().fence_scope, static_cast<std::uint32_t>(FenceScopeState::Committed));
  CHECK(outcome.value().closure_complete);
  CHECK_NE(outcome.value().closure_members, std::size_t{0});
  CHECK_NE(outcome.value().grants_fenced, std::size_t{0});
  CHECK_NE(outcome.value().closure_digest, std::uint64_t{0});

  // Every dependent bound to the failed generation lost its authority.
  for (const PathId id : affected) {
    Result<AuthorityQueryResponse> query = ask_authority(session, DependentRef::path(id));
    CHECK(query.ok());
    if (!query.ok()) continue;
    CHECK(!query.value().has_authority);
    CHECK_EQ(query.value().outcome, Code::Fenced);
    CHECK_NE(query.value().fenced_generations, std::size_t{0});
  }
  // A dependent on an unrelated generation is untouched: no cross-generation contamination.
  for (const PathId id : untouched) {
    Result<AuthorityQueryResponse> query = ask_authority(session, DependentRef::path(id));
    CHECK(query.ok());
    if (!query.ok()) continue;
    CHECK(query.value().has_authority);
    CHECK_EQ(query.value().outcome, Code::Ok);
  }
  // Service restoration is refused while the fence stands, and it is refused as a fence.
  {
    Result<RestoreQueryResponse> restore =
        ask_restore(session, DependentRef::path(affected.front()));
    CHECK(restore.ok());
    if (restore.ok()) {
      CHECK(!restore.value().may_restore);
      CHECK(!restore.value().effect_verified);
      CHECK_EQ(restore.value().outcome, Code::Fenced);
    }
  }
  // The worker's own snapshot agrees about what was committed.
  {
    Result<SnapshotResponse> snapshot = ask_snapshot(session);
    CHECK(snapshot.ok());
    if (snapshot.ok()) {
      CHECK_EQ(snapshot.value().failures, std::size_t{1});
      CHECK_EQ(snapshot.value().fences, std::size_t{1});
      CHECK_EQ(snapshot.value().epoch, worker.epoch);
    }
  }
  CHECK(session.close().ok());
}

// ---------------------------------------------------------------------------------------------
// 3. Session isolation: forged authority and replayed sequences are refused and never executed.
// ---------------------------------------------------------------------------------------------

SFF_TEST(forged_session_epoch_boot_and_replayed_sequence_are_refused_and_not_executed) {
  CHECK(context().valid);
  if (!context().valid) return;
  ServeWorker& worker = serve_worker();
  CHECK(worker.ready);
  if (!worker.ready) return;

  Result<Fabric> built = build_fabric(FabricSpec{});
  CHECK(built.ok());
  if (!built.ok()) return;
  const Fabric& fabric = built.value();
  const SwitchKey target = fabric.spine_keys.at(1);  // still healthy: an execution would show
  const std::vector<PathId> dependents = paths_through(fabric, target);
  CHECK(!dependents.empty());
  if (dependents.empty()) return;

  Result<std::unique_ptr<FrameClient>> client = connect_and_handshake(worker, "isolation");
  CHECK(client.ok());
  if (!client.ok()) return;

  // What the worker had committed *before* the forgeries: the forgeries must not move these.
  std::size_t failures_before = 0;
  std::size_t fences_before = 0;
  {
    Result<SnapshotResponse> before = ask_snapshot(*client.value());
    CHECK(before.ok());
    if (!before.ok()) return;
    failures_before = before.value().failures;
    fences_before = before.value().fences;
  }

  RawClient raw;
  CHECK(raw.connect_loopback(worker.port));
  RawSession session;
  CHECK(raw_handshake(raw, session));
  if (!session.opened) return;
  CHECK_EQ(session.epoch.raw(), worker.epoch);
  CHECK_NE(session.boot_digest, std::uint64_t{0});

  // Every forgery below requests the same real mutation: fence the healthy spine generation.
  FailoverRequest declaration;
  declaration.subject = target;
  declaration.source = EvidenceSource::FabricManager;
  declaration.observed_at_ns = 1000;
  declaration.valid_for_ns = 3600ull * kNanosPerSecond;
  declaration.reason = "SYNTHETIC forged declaration that must never execute";
  const std::vector<std::uint8_t> payload = encode_failover_request(declaration);

  // (a) a different session identity.
  {
    const SessionId forged(session.session.raw() + 1);
    CHECK(raw.send_frame(make_frame(MessageType::DeclareFailure, forged, session.epoch,
                                    session.boot_digest, 2, payload)));
    Frame response;
    CHECK(raw.receive_frame(response));
    const Refusal refusal = refusal_of(response);
    CHECK(refusal.decoded);
    CHECK_EQ(refusal.code, Code::Unauthorized);
  }
  // (b) the right session under an epoch that is not current.
  {
    const CoordinatorEpoch forged(session.epoch.raw() + 1);
    CHECK(raw.send_frame(make_frame(MessageType::DeclareFailure, session.session, forged,
                                    session.boot_digest, 3, payload)));
    Frame response;
    CHECK(raw.receive_frame(response));
    const Refusal refusal = refusal_of(response);
    CHECK(refusal.decoded);
    CHECK_EQ(refusal.code, Code::Stale);
  }
  // (c) the right session and epoch under a boot incarnation that is not current.
  {
    CHECK(raw.send_frame(make_frame(MessageType::DeclareFailure, session.session, session.epoch,
                                    session.boot_digest ^ 0x00FF00FF00FF00FFull, 4, payload)));
    Frame response;
    CHECK(raw.receive_frame(response));
    const Refusal refusal = refusal_of(response);
    CHECK(refusal.decoded);
    CHECK_EQ(refusal.code, Code::Stale);
  }
  // A frame the worker does accept, so the refusals above are attributable to the forgery and not
  // to a blanket refusal of the message type.
  {
    AuthorityQueryRequest query;
    query.dependent = DependentRef::path(dependents.front());
    const std::vector<std::uint8_t> query_payload = encode_authority_query(query);
    CHECK(raw.send_frame(make_frame(MessageType::QueryAuthority, session.session, session.epoch,
                                    session.boot_digest, 6, query_payload)));
    Frame response;
    CHECK(raw.receive_frame(response));
    CHECK_EQ(response.header.type, MessageType::AuthorityResult);
    const Result<AuthorityQueryResponse> decoded = decode_authority_response(response.payload);
    CHECK(decoded.ok());
    if (decoded.ok()) CHECK(decoded.value().has_authority);

    // (d) replay exactly that request sequence: it must be refused.
    CHECK(raw.send_frame(make_frame(MessageType::QueryAuthority, session.session, session.epoch,
                                    session.boot_digest, 6, query_payload)));
    Frame replayed;
    CHECK(raw.receive_frame(replayed));
    const Refusal refusal = refusal_of(replayed);
    CHECK(refusal.decoded);
    CHECK_EQ(refusal.code, Code::Replay);
  }

  // Nothing the forgeries asked for took effect.
  for (const PathId id : dependents) {
    Result<AuthorityQueryResponse> query = ask_authority(*client.value(), DependentRef::path(id));
    CHECK(query.ok());
    if (!query.ok()) continue;
    CHECK(query.value().has_authority);
    CHECK_EQ(query.value().outcome, Code::Ok);
  }
  {
    Result<SnapshotResponse> after = ask_snapshot(*client.value());
    CHECK(after.ok());
    if (after.ok()) {
      CHECK_EQ(after.value().failures, failures_before);
      CHECK_EQ(after.value().fences, fences_before);
    }
  }
  CHECK(client.value()->close().ok());
  raw.close();
}

// ---------------------------------------------------------------------------------------------
// 4(a). Hard kill before any durable commit.
// ---------------------------------------------------------------------------------------------

SFF_TEST(hard_kill_before_ready_leaves_no_partial_record) {
  CHECK(context().valid);
  if (!context().valid) return;

  const std::filesystem::path root = context().scratch / "kill-precommit";
  context().expected_directories.push_back(root);

  Child* child = spawn_child({"serve", "--port", "0", "--root", root.string()}, "kill-precommit");
  CHECK(child != nullptr);
  if (child == nullptr) return;
  // The kill is issued the instant CreateProcess returns: the worker is somewhere between its
  // first instruction and its first durable commit. The property under test holds on both sides of
  // that boundary, so the race is not a source of flakiness.
  CHECK(hard_kill(*child));
  CHECK_EQ(child->exit_code, kKillExitCode);
  CHECK(has_exited(*child));

  // Whatever exists must be replayable: no corruption, no unrecoverable partial record. When the
  // kill landed before the worker created anything at all, replay opens an empty journal and
  // reports zero records - that is the "the durable root is effectively absent" branch of the same
  // property, not a skipped check.
  RunResult first = run_to_completion({"replay", "--root", root.string()}, "replay-precommit");
  CHECK(first.exited);
  CHECK_EQ(first.exit_code, 0u);
  const ReplayReportText report = parse_replay(first.output);
  CHECK(report.parsed);
  if (!report.parsed) {
    close_child(*child);
    return;
  }
  CHECK_EQ(report.corrupt, std::uint64_t{0});
  CHECK_EQ(report.clean, std::uint64_t{0});  // the run never shut down cleanly
  // When the kill demonstrably beat readiness - the capture file holds no READY line - the worker
  // cannot have reached its second durable write either, so the journal holds at most the stream
  // header it was in the middle of appending. The condition is a statement about the observed
  // capture file, not a timing assumption.
  const bool beat_readiness = read_text(child->capture).find("READY") == std::string::npos;
  if (beat_readiness) CHECK(report.records <= std::uint64_t{1});

  // Opening the store physically recovers a genuine torn tail, so a second replay is complete.
  RunResult second = run_to_completion({"replay", "--root", root.string()}, "replay-precommit-2");
  CHECK(second.exited);
  CHECK_EQ(second.exit_code, 0u);
  const ReplayReportText recovered = parse_replay(second.output);
  CHECK(recovered.parsed);
  if (recovered.parsed) {
    CHECK_EQ(recovered.corrupt, std::uint64_t{0});
    CHECK_EQ(recovered.torn, std::uint64_t{0});
    CHECK_EQ(recovered.records, report.records);
    CHECK_EQ(recovered.last_sequence, report.last_sequence);
    CHECK_EQ(recovered.clean, std::uint64_t{0});
  }

  // The recovered journal is a byte-stable, replayable artifact: replaying it never rewrites it.
  const std::filesystem::path journal = root / kJournalName;
  std::string bytes;
  {
    std::ifstream input(journal, std::ios::binary);
    if (input) {
      bytes.assign(std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>());
    }
  }
  RunResult third = run_to_completion({"replay", "--root", root.string()}, "replay-precommit-3");
  CHECK(third.exited);
  CHECK_EQ(third.exit_code, 0u);
  const ReplayReportText stable = parse_replay(third.output);
  CHECK(stable.parsed);
  if (stable.parsed) {
    CHECK_EQ(stable.records, recovered.records);
    CHECK_EQ(stable.torn, std::uint64_t{0});
    CHECK_EQ(stable.corrupt, std::uint64_t{0});
  }
  std::string bytes_after;
  {
    std::ifstream after(journal, std::ios::binary);
    if (after) {
      bytes_after.assign(std::istreambuf_iterator<char>(after), std::istreambuf_iterator<char>());
    }
  }
  CHECK(bytes == bytes_after);

  close_child(*child);
}

// ---------------------------------------------------------------------------------------------
// 4(b). Hard kill after the durable commit but before any acknowledgement.
// ---------------------------------------------------------------------------------------------

SFF_TEST(hard_kill_after_durable_commit_keeps_the_committed_failure) {
  CHECK(context().valid);
  if (!context().valid) return;

  const std::filesystem::path root = context().scratch / "kill-commit";
  const std::filesystem::path marker = context().scratch / "marker-commit.txt";
  context().expected_directories.push_back(root);

  Result<Fabric> built = build_fabric(FabricSpec{});
  CHECK(built.ok());
  if (!built.ok()) return;
  const SwitchKey committed = built.value().spine_keys.at(0);

  Child* holder =
      spawn_child({"hold", "--root", root.string(), "--marker", marker.string()}, "kill-hold");
  CHECK(holder != nullptr);
  if (holder == nullptr) return;
  // The marker is written only after the commit has been forced to stable storage, so waiting for
  // it is waiting for durability rather than guessing at a moment.
  CHECK(wait_for_file(marker));
  CHECK(!has_exited(*holder));  // genuinely blocked on stdin, not finished
  CHECK(hard_kill(*holder));
  CHECK_EQ(holder->exit_code, kKillExitCode);

  RunResult replayed = run_to_completion({"replay", "--root", root.string()}, "replay-commit");
  CHECK(replayed.exited);
  CHECK_EQ(replayed.exit_code, 0u);
  const ReplayReportText report = parse_replay(replayed.output);
  CHECK(report.parsed);
  if (report.parsed) {
    CHECK_EQ(report.corrupt, std::uint64_t{0});
    CHECK_EQ(report.torn, std::uint64_t{0});
    CHECK_EQ(report.records, std::uint64_t{2});  // stream header + committed failure
    CHECK_EQ(report.clean, std::uint64_t{0});    // killed: the previous shutdown was not clean
    CHECK_EQ(report.last_sequence, std::uint64_t{2});
  }
  CHECK(output_has_lineage(replayed.output, "failure", committed));

  std::error_code code;
  std::filesystem::remove(marker, code);
  close_child(*holder);
}

// ---------------------------------------------------------------------------------------------
// 4(c) and 5. Hard kill after the failover was applied but before the client read the response,
// then a restart over the same durable root.
// ---------------------------------------------------------------------------------------------

SFF_TEST(kill_after_failover_then_restart_never_resurrects_authority) {
  CHECK(context().valid);
  if (!context().valid) return;
  ServeWorker& worker = serve_worker();
  CHECK(worker.ready);
  if (!worker.ready) return;

  Result<Fabric> built = build_fabric(FabricSpec{});
  CHECK(built.ok());
  if (!built.ok()) return;
  const Fabric& fabric = built.value();
  const SwitchKey second = fabric.spine_keys.at(1);

  // The request goes out on a socket this test never reads from again, so the response is unread by
  // construction, and the worker is killed the moment the fence record is durable on disk.
  RawClient raw;
  CHECK(raw.connect_loopback(worker.port));
  RawSession session;
  CHECK(raw_handshake(raw, session));
  if (!session.opened) return;

  FailoverRequest declaration;
  declaration.subject = second;
  declaration.source = EvidenceSource::FabricManager;
  declaration.observed_at_ns = 1000;
  declaration.valid_for_ns = 3600ull * kNanosPerSecond;
  declaration.reason = "SYNTHETIC failover whose acknowledgement is never read";
  CHECK(raw.send_frame(make_frame(MessageType::DeclareFailure, session.session, session.epoch,
                                  session.boot_digest, 2,
                                  encode_failover_request(declaration))));
  // Bounded readiness poll on the durable artifact itself: this places the kill exactly after the
  // commit, without any sleep-based guess about how fast the worker happens to be.
  CHECK(wait_for_durable_fence(worker.journal(), second));
  CHECK(!has_exited(*worker.child));
  CHECK(hard_kill(*worker.child));
  CHECK_EQ(worker.child->exit_code, kKillExitCode);
  raw.close();
  close_child(*worker.child);

  // The failure lineage and both fences survived the kill; the previous shutdown was not clean.
  RunResult replayed =
      run_to_completion({"replay", "--root", worker.root.string()}, "replay-after-kill");
  CHECK(replayed.exited);
  CHECK_EQ(replayed.exit_code, 0u);
  const ReplayReportText report = parse_replay(replayed.output);
  CHECK(report.parsed);
  if (report.parsed) {
    CHECK_EQ(report.corrupt, std::uint64_t{0});
    CHECK_EQ(report.torn, std::uint64_t{0});
    CHECK_EQ(report.clean, std::uint64_t{0});
  }
  CHECK(output_has_lineage(replayed.output, "failure", fabric.spine_keys.at(0)));
  CHECK(output_has_lineage(replayed.output, "failure", second));
  CHECK(output_has_lineage(replayed.output, "fence", fabric.spine_keys.at(0)));
  CHECK(output_has_lineage(replayed.output, "fence", second));

  // Restart continuity: a brand new operating-system process over the same durable root.
  Child* restarted =
      spawn_child({"serve", "--port", "0", "--root", worker.root.string()}, "serve-restarted");
  CHECK(restarted != nullptr);
  if (restarted == nullptr) return;
  std::string line;
  ReadyInfo info;
  const bool ready = wait_for_line(restarted->capture, "READY", line) && parse_ready(line, info);
  CHECK(ready);
  if (!ready) {
    hard_kill(*restarted);
    close_child(*restarted);
    return;
  }
  // Epoch and boot incarnation advanced strictly, so no authority minted by the killed process can
  // be mistaken for authority under the new one.
  CHECK_LT(worker.epoch, info.epoch);
  CHECK_LT(worker.boot, info.boot);
  CHECK_NE(info.port, 0);

  ServeWorker next;
  next.attempted = true;
  next.ready = true;
  next.child = restarted;
  next.port = info.port;
  next.epoch = info.epoch;
  next.boot = info.boot;
  next.root = worker.root;

  {
    Result<std::unique_ptr<FrameClient>> client = connect_and_handshake(next, "restarted");
    CHECK(client.ok());
    if (!client.ok()) return;
    // The fence survived: the restarted runtime re-installs the very same topology, and every
    // dependent that would otherwise be granted authority for a fenced generation is refused it.
    for (const PathId id : fabric.path_ids) {
      Result<AuthorityQueryResponse> query = ask_authority(*client.value(), DependentRef::path(id));
      CHECK(query.ok());
      if (!query.ok()) continue;
      CHECK(!query.value().has_authority);
      CHECK_NE(query.value().outcome, Code::Ok);
    }
    Result<SnapshotResponse> snapshot = ask_snapshot(*client.value());
    CHECK(snapshot.ok());
    if (snapshot.ok()) {
      CHECK_EQ(snapshot.value().epoch, info.epoch);
      CHECK_EQ(snapshot.value().boot_ordinal, info.boot);
      CHECK_EQ(snapshot.value().failures, std::size_t{2});
      CHECK_EQ(snapshot.value().fences, std::size_t{2});
    }
    // Restoration is still refused after the restart, and it is never reported as permitted.
    //
    // Observation (reported, not asserted as desirable): the *reason* degrades here. A restarted
    // runtime holds no grants for these dependents - install_topology refuses to mint one for a
    // fenced generation, and grants are never durable - so evaluate_restore has an empty bound
    // vector and cannot name the blocking generation. The decision is still fail-closed
    // (may_restore false, outcome never Ok), but the explanation becomes "no forwarding authority
    // was ever granted" instead of "a bound generation is fenced", even though the fence itself is
    // demonstrably durable and in force, as the snapshot and the grants above show.
    Result<RestoreQueryResponse> restore =
        ask_restore(*client.value(), DependentRef::path(fabric.path_ids.at(0)));
    CHECK(restore.ok());
    if (restore.ok()) {
      CHECK(!restore.value().may_restore);
      CHECK(!restore.value().effect_verified);
      CHECK_NE(restore.value().outcome, Code::Ok);
    }
    CHECK(client.value()->close().ok());
  }

  // Shut the restarted worker down through its real end-of-file path, so its journal ends with a
  // clean shutdown marker and the next reader can tell the two apart.
  CHECK(release_stdin(*restarted));
  CHECK(wait_for_exit(*restarted));
  CHECK_EQ(restarted->exit_code, 0u);
  close_child(*restarted);

  RunResult after_shutdown =
      run_to_completion({"replay", "--root", worker.root.string()}, "replay-clean");
  CHECK(after_shutdown.exited);
  CHECK_EQ(after_shutdown.exit_code, 0u);
  const ReplayReportText clean = parse_replay(after_shutdown.output);
  CHECK(clean.parsed);
  if (clean.parsed) {
    CHECK_EQ(clean.corrupt, std::uint64_t{0});
    CHECK_EQ(clean.torn, std::uint64_t{0});
    CHECK_EQ(clean.clean, std::uint64_t{1});  // this run did shut down cleanly
  }
}

// ---------------------------------------------------------------------------------------------
// 6. Cleanliness: no process outlives the test and no temporary file is left behind.
// ---------------------------------------------------------------------------------------------

SFF_TEST(every_spawned_process_exited_and_no_temp_file_is_leaked) {
  for (const std::unique_ptr<Child>& child : spawned()) {
    const bool exited = has_exited(*child);
    CHECK(exited);
    if (!exited) {
      // A leaked process would also hang the suite; reap it so the failure is reported rather than
      // turning into a hang.
      hard_kill(*child);
    }
    CHECK(child->reaped);
    close_child(*child);
  }

  if (!context().valid) return;

  // Every remaining entry in the scratch directory must be one this suite deliberately created.
  std::error_code code;
  std::vector<std::filesystem::path> leftovers;
  for (const std::filesystem::directory_entry& entry :
       std::filesystem::directory_iterator(context().scratch, code)) {
    const bool expected =
        std::find(context().expected_directories.begin(), context().expected_directories.end(),
                  entry.path()) != context().expected_directories.end();
    if (!expected) leftovers.push_back(entry.path());
  }
  CHECK_EQ(leftovers.size(), std::size_t{0});
  for (const std::filesystem::path& leaked : leftovers) {
    std::printf("  LEAKED %s\n", leaked.string().c_str());
  }

  // And the scratch directory itself is removed: the suite leaves nothing behind.
  std::filesystem::remove_all(context().scratch, code);
  CHECK(!std::filesystem::exists(context().scratch));
}

int main(int argc, char** argv) {
  Context& ctx = context();
  if (argc >= 3) {
    ctx.worker = std::filesystem::path(argv[1]);
    ctx.scratch = std::filesystem::path(argv[2]);
    std::error_code code;
    std::filesystem::create_directories(ctx.scratch, code);
    ctx.valid = !code && std::filesystem::exists(ctx.worker) &&
                std::filesystem::is_directory(ctx.scratch);
  }
  if (!ctx.valid) {
    std::printf("usage: test_multiprocess <mp_worker.exe> <scratch directory>\n");
  }

  // The raw loopback sockets used by the isolation cases need a live Winsock stack.
  WSADATA data{};
  const bool network = WSAStartup(MAKEWORD(2, 2), &data) == 0;
  const int result = sfftest::run_all();
  if (network) WSACleanup();
  return result;
}
